# Clipto Daily Backup Script
# Auto-generated by Clipto Resurrection Protocol
# Generated: 2026-01-21 14:44:51

$source = "C:\Users\Erik\AppData\Roaming\Clipto"
$destination = "C:\Users\Erik\OneDrive\CliptoBackups"
$timestamp = Get-Date -Format 'yyyyMMdd'
$dailyBackup = "$destination\Clipto_$timestamp"

# Check if source has data
if (-not (Test-Path $source)) {
    Write-Host "No Clipto data to backup yet" -ForegroundColor Gray
    exit 0
}

# Check if today's backup already exists
if (Test-Path $dailyBackup) {
    Write-Host "Today's backup already exists" -ForegroundColor Gray
    exit 0
}

# Create backup
try {
    Copy-Item -Path $source -Destination $dailyBackup -Recurse -Force
    Write-Host "✅ Backup created: $dailyBackup" -ForegroundColor Green
    
    # Cleanup old backups (keep last 7 days)
    Get-ChildItem $destination -Directory | 
        Where-Object { $_.Name -like "Clipto_*" } |
        Sort-Object CreationTime -Descending | 
        Select-Object -Skip 7 | 
        Remove-Item -Recurse -Force
    
    Write-Host "✅ Old backups cleaned up (keeping last 7 days)" -ForegroundColor Green
} catch {
    Write-Host "❌ Backup failed: $_" -ForegroundColor Red
    exit 1
}
