# ============================================
# CLIPTO RESURRECTION - PHASE 1: INSTALLATION
# Step 1.3: Automated Backup Configuration
# ============================================

Write-Host ""
Write-Host "=== PHASE 1.3: AUTOMATED BACKUP SETUP ===" -ForegroundColor Cyan
Write-Host ""

# Configuration
$cliptoDataPath = "$env:APPDATA\Clipto"
$oneDriveBackupBase = "$env:USERPROFILE\OneDrive\CliptoBackups"
$localBackupBase = "$env:USERPROFILE\Documents\CliptoBackups"

# Determine backup location
$backupBasePath = if (Test-Path "$env:USERPROFILE\OneDrive") {
    Write-Host "📁 OneDrive detected - using cloud backup location" -ForegroundColor Cyan
    $oneDriveBackupBase
}
else {
    Write-Host "📁 OneDrive not available - using local backup" -ForegroundColor Yellow
    $localBackupBase
}

Write-Host "   Backup location: $backupBasePath" -ForegroundColor Gray
Write-Host ""

# Create backup directory
if (-not (Test-Path $backupBasePath)) {
    New-Item -ItemType Directory -Path $backupBasePath -Force | Out-Null
    Write-Host "✅ Created backup directory" -ForegroundColor Green
}
else {
    Write-Host "✅ Backup directory exists" -ForegroundColor Green
}

Write-Host ""

# Create the daily backup script
$dailyBackupScriptPath = "$backupBasePath\CliptoDailyBackup.ps1"

$backupScriptContent = @"
# Clipto Daily Backup Script
# Auto-generated by Clipto Resurrection Protocol
# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

`$source = "$cliptoDataPath"
`$destination = "$backupBasePath"
`$timestamp = Get-Date -Format 'yyyyMMdd'
`$dailyBackup = "`$destination\Clipto_`$timestamp"

# Check if source has data
if (-not (Test-Path `$source)) {
    Write-Host "No Clipto data to backup yet" -ForegroundColor Gray
    exit 0
}

# Check if today's backup already exists
if (Test-Path `$dailyBackup) {
    Write-Host "Today's backup already exists" -ForegroundColor Gray
    exit 0
}

# Create backup
try {
    Copy-Item -Path `$source -Destination `$dailyBackup -Recurse -Force
    Write-Host "✅ Backup created: `$dailyBackup" -ForegroundColor Green
    
    # Cleanup old backups (keep last 7 days)
    Get-ChildItem `$destination -Directory | 
        Where-Object { `$_.Name -like "Clipto_*" } |
        Sort-Object CreationTime -Descending | 
        Select-Object -Skip 7 | 
        Remove-Item -Recurse -Force
    
    Write-Host "✅ Old backups cleaned up (keeping last 7 days)" -ForegroundColor Green
} catch {
    Write-Host "❌ Backup failed: `$_" -ForegroundColor Red
    exit 1
}
"@

Write-Host "📝 Creating daily backup script..." -ForegroundColor Cyan
$backupScriptContent | Out-File -FilePath $dailyBackupScriptPath -Encoding UTF8 -Force
Write-Host "✅ Script created: $dailyBackupScriptPath" -ForegroundColor Green
Write-Host ""

# Test the backup script
Write-Host "🧪 Testing backup script..." -ForegroundColor Cyan
try {
    & $dailyBackupScriptPath
    Write-Host "✅ Backup script test passed" -ForegroundColor Green
}
catch {
    Write-Host "⚠️  Backup script test failed: $_" -ForegroundColor Yellow
    Write-Host "   (This is normal if you haven't used Clipto yet)" -ForegroundColor Gray
}

Write-Host ""

# Offer to create scheduled task
Write-Host "📅 OPTIONAL: Schedule Daily Backups" -ForegroundColor Yellow
Write-Host ""
Write-Host "Would you like to create a Windows Task Scheduler job?" -ForegroundColor Cyan
Write-Host "This will run the backup script daily at 11:00 PM." -ForegroundColor Gray
Write-Host ""
$response = Read-Host "Create scheduled task? (Y/N)"

if ($response -eq 'Y' -or $response -eq 'y') {
    # Require Administrator for Task Scheduler
    if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
        Write-Host ""
        Write-Host "⚠️  Task Scheduler requires Administrator privileges" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "To create the scheduled task later:" -ForegroundColor Cyan
        Write-Host "  1. Run PowerShell as Administrator" -ForegroundColor Gray
        Write-Host "  2. Run this command:" -ForegroundColor Gray
        Write-Host ""
        Write-Host "schtasks /create /tn `"Clipto Daily Backup`" /tr `"powershell.exe -ExecutionPolicy Bypass -File '$dailyBackupScriptPath'`" /sc daily /st 23:00" -ForegroundColor White
        Write-Host ""
    }
    else {
        try {
            $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -NoProfile -File `"$dailyBackupScriptPath`""
            $trigger = New-ScheduledTaskTrigger -Daily -At "11:00PM"
            $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
            
            Register-ScheduledTask -TaskName "Clipto Daily Backup" -Action $action -Trigger $trigger -Settings $settings -Description "Daily backup of Clipto data" -Force | Out-Null
            
            Write-Host "✅ Scheduled task created successfully!" -ForegroundColor Green
            Write-Host "   Task name: Clipto Daily Backup" -ForegroundColor Yellow
            Write-Host "   Schedule: Daily at 11:00 PM" -ForegroundColor Yellow
        }
        catch {
            Write-Host "❌ Failed to create scheduled task: $_" -ForegroundColor Red
        }
    }
}
else {
    Write-Host ""
    Write-Host "⏭️  Skipped scheduled task creation" -ForegroundColor Gray
    Write-Host ""
    Write-Host "To backup manually, run:" -ForegroundColor Cyan
    Write-Host "  $dailyBackupScriptPath" -ForegroundColor White
}

Write-Host ""
Write-Host "=== PHASE 1.3 COMPLETE ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "📋 Backup Configuration Summary:" -ForegroundColor Yellow
Write-Host "  • Backup script: $dailyBackupScriptPath" -ForegroundColor Gray
Write-Host "  • Backup location: $backupBasePath" -ForegroundColor Gray
Write-Host "  • Retention: Last 7 days" -ForegroundColor Gray
Write-Host ""
Write-Host "=== PHASE 1 COMPLETE! ===" -ForegroundColor Green
Write-Host ""
Write-Host "🎉 Clipto is now installed and configured!" -ForegroundColor Green
Write-Host ""
Write-Host "✅ Installation complete" -ForegroundColor Green
Write-Host "✅ Air-gap firewall active" -ForegroundColor Green
Write-Host "✅ Daily backup configured" -ForegroundColor Green
Write-Host ""
Write-Host "🚀 You can now launch Clipto!" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  • Launch Clipto from Start Menu" -ForegroundColor Gray
Write-Host "  • Create some test notes" -ForegroundColor Gray
Write-Host "  • Report back if you encounter issues" -ForegroundColor Gray
Write-Host ""
